[project]
name = "combot"
version = "0.1.0"
description = "Combat Robot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
